// Code generated by scripts/generate-web-api-contract.mjs. DO NOT EDIT.

import { apiRequest } from "@/api/client";
import { apiEndpoints } from "@/api/endpoints";

/**
 * Health check
 * @param {object} [options]
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").HealthResponse>}
 */
export function getHealth(options = {}) {
  return apiRequest(apiEndpoints.getHealth, options);
}

/**
 * Readiness check
 * @param {object} [options]
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").ReadinessResponse>}
 */
export function getReady(options = {}) {
  return apiRequest(apiEndpoints.getReady, options);
}

/**
 * Runtime metrics
 * @param {object} [options]
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<string>}
 */
export function getMetrics(options = {}) {
  return apiRequest(apiEndpoints.getMetrics, options);
}

/**
 * Public application configuration
 * @param {object} [options]
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").AppConfig>}
 */
export function getAppConfig(options = {}) {
  return apiRequest(apiEndpoints.getAppConfig, options);
}

/**
 * Login
 * @param {object} [options]
 * @param {import("./types").LoginRequest} options.body
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").LoginResponse>}
 */
export function postAuthLogin(options = {}) {
  return apiRequest(apiEndpoints.postAuthLogin, options);
}

/**
 * Logout
 * @param {object} [options]
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").OkResult>}
 */
export function postAuthLogout(options = {}) {
  return apiRequest(apiEndpoints.postAuthLogout, options);
}

/**
 * Current user profile
 * @param {object} [options]
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").AuthProfile>}
 */
export function getAuthProfile(options = {}) {
  return apiRequest(apiEndpoints.getAuthProfile, options);
}

/**
 * Update current user profile
 * @param {object} [options]
 * @param {import("./types").UpdateProfileRequest} options.body
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").PublicUser>}
 */
export function putAuthProfile(options = {}) {
  return apiRequest(apiEndpoints.putAuthProfile, options);
}

/**
 * Change current user password
 * @param {object} [options]
 * @param {import("./types").ChangePasswordRequest} options.body
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").OkResult>}
 */
export function putAuthPassword(options = {}) {
  return apiRequest(apiEndpoints.putAuthPassword, options);
}

/**
 * Dashboard summary
 * @param {object} [options]
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").DashboardSummary>}
 */
export function getDashboardSummary(options = {}) {
  return apiRequest(apiEndpoints.getDashboardSummary, options);
}

/**
 * List users
 * @param {object} [options]
 * @param {{ page?: number, page_size?: number, keyword?: string, status?: string }} [options.query]
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").UserPage>}
 */
export function getSystemUsers(options = {}) {
  return apiRequest(apiEndpoints.getSystemUsers, options);
}

/**
 * Create user
 * @param {object} [options]
 * @param {import("./types").CreateUserRequest} options.body
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").PublicUser>}
 */
export function postSystemUsers(options = {}) {
  return apiRequest(apiEndpoints.postSystemUsers, options);
}

/**
 * Get user
 * @param {object} [options]
 * @param {{ id: number }} options.params
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").PublicUser>}
 */
export function getSystemUsersId(options = {}) {
  return apiRequest(apiEndpoints.getSystemUsersId, options);
}

/**
 * Update user
 * @param {object} [options]
 * @param {{ id: number }} options.params
 * @param {import("./types").UpdateUserRequest} options.body
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").PublicUser>}
 */
export function putSystemUsersId(options = {}) {
  return apiRequest(apiEndpoints.putSystemUsersId, options);
}

/**
 * Delete user
 * @param {object} [options]
 * @param {{ id: number }} options.params
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").OkResult>}
 */
export function deleteSystemUsersId(options = {}) {
  return apiRequest(apiEndpoints.deleteSystemUsersId, options);
}

/**
 * Update user status
 * @param {object} [options]
 * @param {{ id: number }} options.params
 * @param {import("./types").UserStatusRequest} options.body
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").PublicUser>}
 */
export function patchSystemUsersIdStatus(options = {}) {
  return apiRequest(apiEndpoints.patchSystemUsersIdStatus, options);
}

/**
 * List roles
 * @param {object} [options]
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").RoleList>}
 */
export function getSystemRoles(options = {}) {
  return apiRequest(apiEndpoints.getSystemRoles, options);
}

/**
 * Create role
 * @param {object} [options]
 * @param {import("./types").RoleRequest} options.body
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").Role>}
 */
export function postSystemRoles(options = {}) {
  return apiRequest(apiEndpoints.postSystemRoles, options);
}

/**
 * Update role
 * @param {object} [options]
 * @param {{ id: number }} options.params
 * @param {import("./types").RoleRequest} options.body
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").Role>}
 */
export function putSystemRolesId(options = {}) {
  return apiRequest(apiEndpoints.putSystemRolesId, options);
}

/**
 * Delete role
 * @param {object} [options]
 * @param {{ id: number }} options.params
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").OkResult>}
 */
export function deleteSystemRolesId(options = {}) {
  return apiRequest(apiEndpoints.deleteSystemRolesId, options);
}

/**
 * List system permissions
 * @param {object} [options]
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").PermissionDefinitionList>}
 */
export function getSystemPermissions(options = {}) {
  return apiRequest(apiEndpoints.getSystemPermissions, options);
}

/**
 * List menus
 * @param {object} [options]
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").MenuList>}
 */
export function getSystemMenus(options = {}) {
  return apiRequest(apiEndpoints.getSystemMenus, options);
}

/**
 * Create menu
 * @param {object} [options]
 * @param {import("./types").MenuRequest} options.body
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").Menu>}
 */
export function postSystemMenus(options = {}) {
  return apiRequest(apiEndpoints.postSystemMenus, options);
}

/**
 * Update menu
 * @param {object} [options]
 * @param {{ id: number }} options.params
 * @param {import("./types").MenuRequest} options.body
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").Menu>}
 */
export function putSystemMenusId(options = {}) {
  return apiRequest(apiEndpoints.putSystemMenusId, options);
}

/**
 * Delete menu
 * @param {object} [options]
 * @param {{ id: number }} options.params
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").OkResult>}
 */
export function deleteSystemMenusId(options = {}) {
  return apiRequest(apiEndpoints.deleteSystemMenusId, options);
}

/**
 * List registered modules
 * @param {object} [options]
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").ModuleList>}
 */
export function getSystemModules(options = {}) {
  return apiRequest(apiEndpoints.getSystemModules, options);
}

/**
 * List dictionaries
 * @param {object} [options]
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").DictionaryList>}
 */
export function getSystemDictionaries(options = {}) {
  return apiRequest(apiEndpoints.getSystemDictionaries, options);
}

/**
 * Create dictionary
 * @param {object} [options]
 * @param {import("./types").DictionaryRequest} options.body
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").Dictionary>}
 */
export function postSystemDictionaries(options = {}) {
  return apiRequest(apiEndpoints.postSystemDictionaries, options);
}

/**
 * Get dictionary by code
 * @param {object} [options]
 * @param {{ code: string }} options.params
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").Dictionary>}
 */
export function getSystemDictionariesCodeCode(options = {}) {
  return apiRequest(apiEndpoints.getSystemDictionariesCodeCode, options);
}

/**
 * Update dictionary
 * @param {object} [options]
 * @param {{ id: number }} options.params
 * @param {import("./types").DictionaryRequest} options.body
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").Dictionary>}
 */
export function putSystemDictionariesId(options = {}) {
  return apiRequest(apiEndpoints.putSystemDictionariesId, options);
}

/**
 * Delete dictionary
 * @param {object} [options]
 * @param {{ id: number }} options.params
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").OkResult>}
 */
export function deleteSystemDictionariesId(options = {}) {
  return apiRequest(apiEndpoints.deleteSystemDictionariesId, options);
}

/**
 * List settings
 * @param {object} [options]
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").SettingList>}
 */
export function getSystemSettings(options = {}) {
  return apiRequest(apiEndpoints.getSystemSettings, options);
}

/**
 * Create setting
 * @param {object} [options]
 * @param {import("./types").SettingRequest} options.body
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").Setting>}
 */
export function postSystemSettings(options = {}) {
  return apiRequest(apiEndpoints.postSystemSettings, options);
}

/**
 * Update setting
 * @param {object} [options]
 * @param {{ id: number }} options.params
 * @param {import("./types").SettingRequest} options.body
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").Setting>}
 */
export function putSystemSettingsId(options = {}) {
  return apiRequest(apiEndpoints.putSystemSettingsId, options);
}

/**
 * Delete setting
 * @param {object} [options]
 * @param {{ id: number }} options.params
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").OkResult>}
 */
export function deleteSystemSettingsId(options = {}) {
  return apiRequest(apiEndpoints.deleteSystemSettingsId, options);
}

/**
 * List audit logs
 * @param {object} [options]
 * @param {{ page?: number, page_size?: number, keyword?: string, actor?: string, action?: string, resource?: string, resource_id?: string }} [options.query]
 * @param {boolean} [options.auth]
 * @param {AbortSignal} [options.signal]
 * @returns {Promise<import("./types").AuditLogPage>}
 */
export function getSystemAuditLogs(options = {}) {
  return apiRequest(apiEndpoints.getSystemAuditLogs, options);
}
