// Code generated by scripts/generate-web-api-contract.mjs. DO NOT EDIT.

/**
 * @typedef {object} AppConfig
 * @property {string} [name]
 * @property {string} [title]
 * @property {string} [environment]
 */

/**
 * @typedef {object} HealthResponse
 * @property {string} name
 * @property {string} environment
 * @property {string} status
 * @property {string} time
 */

/**
 * @typedef {object} ReadinessCheck
 * @property {string} name
 * @property {string} status
 * @property {string} [error]
 */

/**
 * @typedef {object} ReadinessResponse
 * @property {string} status
 * @property {Array<ReadinessCheck>} checks
 * @property {string} time
 */

/**
 * @typedef {object} DashboardSummary
 * @property {number} user_count
 * @property {number} role_count
 * @property {number} menu_count
 * @property {number} audit_log_count
 * @property {number} active_user_count
 */

/**
 * @typedef {object} FieldError
 * @property {string} field
 * @property {string} message
 */

/**
 * @typedef {object} ValidationErrorData
 * @property {Array<FieldError>} [fields]
 */

/**
 * @typedef {object} ValidationErrorEnvelope
 * @property {number} [code]
 * @property {string} [message]
 * @property {ValidationErrorData} [data]
 * @property {string} [request_id]
 */

/**
 * @typedef {object} ErrorEnvelope
 * @property {number} [code]
 * @property {string} [message]
 * @property {unknown} [data]
 * @property {string} [request_id]
 */

/**
 * @typedef {object} LoginRequest
 * @property {string} username
 * @property {string} password
 */

/**
 * @typedef {object} LoginResponse
 * @property {string} token
 * @property {number} expires_at
 * @property {PublicUser} user
 */

/**
 * @typedef {object} AuthProfile
 * @property {PublicUser} user
 * @property {Array<number>} roles
 * @property {Array<string>} permissions
 * @property {Array<Menu>} menus
 */

/**
 * @typedef {object} PublicUser
 * @property {number} id
 * @property {string} username
 * @property {string} nickname
 * @property {string} email
 * @property {string} phone
 * @property {string} avatar
 * @property {Array<number>} role_ids
 * @property {"active"|"disabled"} status
 * @property {string} created_at
 * @property {string} updated_at
 * @property {string} [last_login_at]
 */

/**
 * @typedef {object} UserPage
 * @property {Array<PublicUser>} items
 * @property {number} total
 * @property {number} page
 * @property {number} page_size
 */

/**
 * @typedef {object} Role
 * @property {number} id
 * @property {string} name
 * @property {string} code
 * @property {string} description
 * @property {Array<string>} permissions
 * @property {string} created_at
 * @property {string} updated_at
 */

/**
 * @typedef {Array<Role>} RoleList
 */

/**
 * @typedef {object} PermissionDefinition
 * @property {string} code
 * @property {string} name
 * @property {string} module
 * @property {string} description
 */

/**
 * @typedef {Array<PermissionDefinition>} PermissionDefinitionList
 */

/**
 * @typedef {object} Menu
 * @property {number} id
 * @property {number} parent_id
 * @property {string} title
 * @property {string} name
 * @property {string} path
 * @property {string} icon
 * @property {string} component
 * @property {string} permission
 * @property {number} sort
 * @property {boolean} hidden
 * @property {Array<Menu>} [children]
 */

/**
 * @typedef {Array<Menu>} MenuList
 */

/**
 * @typedef {object} Module
 * @property {string} name
 * @property {string} title
 * @property {string} version
 * @property {string} description
 * @property {Array<PermissionDefinition>} permissions
 * @property {Array<ModuleBackendRoute>} backend_routes
 * @property {Array<ModuleMenuEntry>} menus
 * @property {Array<ModuleFrontendRoute>} frontend_routes
 * @property {Array<ModuleMigrationSet>} migrations
 */

/**
 * @typedef {object} ModuleBackendRoute
 * @property {string} name
 * @property {string} method
 * @property {string} path
 * @property {boolean} public
 * @property {string} permission
 * @property {string} summary
 */

/**
 * @typedef {object} ModuleMenuEntry
 * @property {string} name
 * @property {string} parent
 * @property {string} title
 * @property {string} path
 * @property {string} icon
 * @property {string} component
 * @property {string} permission
 * @property {number} sort
 * @property {boolean} hidden
 */

/**
 * @typedef {object} ModuleFrontendRoute
 * @property {string} name
 * @property {string} path
 * @property {string} component
 * @property {string} title
 * @property {string} permission
 */

/**
 * @typedef {object} ModuleMigrationSet
 * @property {string} driver
 * @property {string} dir
 * @property {string} seeds_dir
 */

/**
 * @typedef {Array<Module>} ModuleList
 */

/**
 * @typedef {object} DictionaryItem
 * @property {string} label
 * @property {string} value
 * @property {number} sort
 */

/**
 * @typedef {object} Dictionary
 * @property {number} id
 * @property {string} code
 * @property {string} name
 * @property {Array<DictionaryItem>} items
 * @property {string} created_at
 * @property {string} updated_at
 */

/**
 * @typedef {Array<Dictionary>} DictionaryList
 */

/**
 * @typedef {object} Setting
 * @property {number} id
 * @property {string} key
 * @property {unknown} value
 * @property {string} description
 * @property {string} created_at
 * @property {string} updated_at
 */

/**
 * @typedef {Array<Setting>} SettingList
 */

/**
 * @typedef {object} AuditLog
 * @property {number} id
 * @property {number} actor_id
 * @property {string} actor
 * @property {string} action
 * @property {string} resource
 * @property {string} resource_id
 * @property {string} ip
 * @property {string} user_agent
 * @property {string} detail
 * @property {string} created_at
 */

/**
 * @typedef {object} AuditLogPage
 * @property {Array<AuditLog>} items
 * @property {number} total
 * @property {number} page
 * @property {number} page_size
 */

/**
 * @typedef {object} OkResult
 * @property {boolean} ok
 */

/**
 * @typedef {object} UpdateProfileRequest
 * @property {string} [nickname]
 * @property {string} [email]
 * @property {string} [phone]
 * @property {string} [avatar]
 */

/**
 * @typedef {object} ChangePasswordRequest
 * @property {string} current_password
 * @property {string} new_password
 */

/**
 * @typedef {object} CreateUserRequest
 * @property {string} username
 * @property {string} password
 * @property {string} [nickname]
 * @property {string} [email]
 * @property {string} [phone]
 * @property {string} [avatar]
 * @property {Array<number>} [role_ids]
 * @property {string} [status]
 */

/**
 * @typedef {object} UpdateUserRequest
 * @property {string} username
 * @property {string} [password]
 * @property {string} [nickname]
 * @property {string} [email]
 * @property {string} [phone]
 * @property {string} [avatar]
 * @property {Array<number>} [role_ids]
 * @property {string} [status]
 */

/**
 * @typedef {object} UserStatusRequest
 * @property {"active"|"disabled"} status
 */

/**
 * @typedef {object} RoleRequest
 * @property {string} name
 * @property {string} code
 * @property {string} [description]
 * @property {Array<string>} [permissions]
 */

/**
 * @typedef {object} MenuRequest
 * @property {number} [parent_id]
 * @property {string} title
 * @property {string} name
 * @property {string} path
 * @property {string} [icon]
 * @property {string} [component]
 * @property {string} [permission]
 * @property {number} [sort]
 * @property {boolean} [hidden]
 */

/**
 * @typedef {object} DictionaryRequest
 * @property {string} code
 * @property {string} name
 * @property {Array<{ label: string, value: string, sort?: number }>} [items]
 */

/**
 * @typedef {object} SettingRequest
 * @property {string} key
 * @property {unknown} [value]
 * @property {string} [description]
 */

export const openApiSchemas = Object.freeze({
  AppConfig: Object.freeze({ type: "object", fields: Object.freeze(["name","title","environment"]), required: Object.freeze([]), fieldTypes: Object.freeze({"name":"string","title":"string","environment":"string"}) }),
  HealthResponse: Object.freeze({ type: "object", fields: Object.freeze(["name","environment","status","time"]), required: Object.freeze(["name","environment","status","time"]), fieldTypes: Object.freeze({"name":"string","environment":"string","status":"string","time":"string"}) }),
  ReadinessCheck: Object.freeze({ type: "object", fields: Object.freeze(["name","status","error"]), required: Object.freeze(["name","status"]), fieldTypes: Object.freeze({"name":"string","status":"string","error":"string"}) }),
  ReadinessResponse: Object.freeze({ type: "object", fields: Object.freeze(["status","checks","time"]), required: Object.freeze(["status","checks","time"]), fieldTypes: Object.freeze({"status":"string","checks":"array","time":"string"}), arrayItemTypes: Object.freeze({"checks":"ReadinessCheck"}) }),
  DashboardSummary: Object.freeze({ type: "object", fields: Object.freeze(["user_count","role_count","menu_count","audit_log_count","active_user_count"]), required: Object.freeze(["user_count","role_count","menu_count","audit_log_count","active_user_count"]), fieldTypes: Object.freeze({"user_count":"number","role_count":"number","menu_count":"number","audit_log_count":"number","active_user_count":"number"}) }),
  FieldError: Object.freeze({ type: "object", fields: Object.freeze(["field","message"]), required: Object.freeze(["field","message"]), fieldTypes: Object.freeze({"field":"string","message":"string"}) }),
  ValidationErrorData: Object.freeze({ type: "object", fields: Object.freeze(["fields"]), required: Object.freeze([]), fieldTypes: Object.freeze({"fields":"array"}), arrayItemTypes: Object.freeze({"fields":"FieldError"}) }),
  ValidationErrorEnvelope: Object.freeze({ type: "object", fields: Object.freeze(["code","message","data","request_id"]), required: Object.freeze([]), fieldTypes: Object.freeze({"code":"number","message":"string","request_id":"string"}), objectFieldTypes: Object.freeze({"data":"ValidationErrorData"}) }),
  ErrorEnvelope: Object.freeze({ type: "object", fields: Object.freeze(["code","message","data","request_id"]), required: Object.freeze([]), fieldTypes: Object.freeze({"code":"number","message":"string","request_id":"string"}) }),
  LoginRequest: Object.freeze({ type: "object", fields: Object.freeze(["username","password"]), required: Object.freeze(["username","password"]), fieldTypes: Object.freeze({"username":"string","password":"string"}) }),
  LoginResponse: Object.freeze({ type: "object", fields: Object.freeze(["token","expires_at","user"]), required: Object.freeze(["token","expires_at","user"]), fieldTypes: Object.freeze({"token":"string","expires_at":"number"}), objectFieldTypes: Object.freeze({"user":"PublicUser"}) }),
  AuthProfile: Object.freeze({ type: "object", fields: Object.freeze(["user","roles","permissions","menus"]), required: Object.freeze(["user","roles","permissions","menus"]), fieldTypes: Object.freeze({"roles":"array","permissions":"array","menus":"array"}), arrayItemTypes: Object.freeze({"menus":"Menu"}), arrayScalarItemTypes: Object.freeze({"roles":"number","permissions":"string"}), objectFieldTypes: Object.freeze({"user":"PublicUser"}) }),
  PublicUser: Object.freeze({ type: "object", fields: Object.freeze(["id","username","nickname","email","phone","avatar","role_ids","status","created_at","updated_at","last_login_at"]), required: Object.freeze(["id","username","nickname","email","phone","avatar","role_ids","status","created_at","updated_at"]), fieldTypes: Object.freeze({"id":"number","username":"string","nickname":"string","email":"string","phone":"string","avatar":"string","role_ids":"array","status":"string","created_at":"string","updated_at":"string","last_login_at":"string"}), enumValues: Object.freeze({"status":["active","disabled"]}), arrayScalarItemTypes: Object.freeze({"role_ids":"number"}) }),
  UserPage: Object.freeze({ type: "object", fields: Object.freeze(["items","total","page","page_size"]), required: Object.freeze(["items","total","page","page_size"]), fieldTypes: Object.freeze({"items":"array","total":"number","page":"number","page_size":"number"}), arrayItemTypes: Object.freeze({"items":"PublicUser"}) }),
  Role: Object.freeze({ type: "object", fields: Object.freeze(["id","name","code","description","permissions","created_at","updated_at"]), required: Object.freeze(["id","name","code","description","permissions","created_at","updated_at"]), fieldTypes: Object.freeze({"id":"number","name":"string","code":"string","description":"string","permissions":"array","created_at":"string","updated_at":"string"}), arrayScalarItemTypes: Object.freeze({"permissions":"string"}) }),
  RoleList: Object.freeze({ type: "array", fields: Object.freeze([]), required: Object.freeze([]), itemType: "Role" }),
  PermissionDefinition: Object.freeze({ type: "object", fields: Object.freeze(["code","name","module","description"]), required: Object.freeze(["code","name","module","description"]), fieldTypes: Object.freeze({"code":"string","name":"string","module":"string","description":"string"}) }),
  PermissionDefinitionList: Object.freeze({ type: "array", fields: Object.freeze([]), required: Object.freeze([]), itemType: "PermissionDefinition" }),
  Menu: Object.freeze({ type: "object", fields: Object.freeze(["id","parent_id","title","name","path","icon","component","permission","sort","hidden","children"]), required: Object.freeze(["id","parent_id","title","name","path","icon","component","permission","sort","hidden"]), fieldTypes: Object.freeze({"id":"number","parent_id":"number","title":"string","name":"string","path":"string","icon":"string","component":"string","permission":"string","sort":"number","hidden":"boolean","children":"array"}), arrayItemTypes: Object.freeze({"children":"Menu"}) }),
  MenuList: Object.freeze({ type: "array", fields: Object.freeze([]), required: Object.freeze([]), itemType: "Menu" }),
  Module: Object.freeze({ type: "object", fields: Object.freeze(["name","title","version","description","permissions","backend_routes","menus","frontend_routes","migrations"]), required: Object.freeze(["name","title","version","description","permissions","backend_routes","menus","frontend_routes","migrations"]), fieldTypes: Object.freeze({"name":"string","title":"string","version":"string","description":"string","permissions":"array","backend_routes":"array","menus":"array","frontend_routes":"array","migrations":"array"}), arrayItemTypes: Object.freeze({"permissions":"PermissionDefinition","backend_routes":"ModuleBackendRoute","menus":"ModuleMenuEntry","frontend_routes":"ModuleFrontendRoute","migrations":"ModuleMigrationSet"}) }),
  ModuleBackendRoute: Object.freeze({ type: "object", fields: Object.freeze(["name","method","path","public","permission","summary"]), required: Object.freeze(["name","method","path","public","permission","summary"]), fieldTypes: Object.freeze({"name":"string","method":"string","path":"string","public":"boolean","permission":"string","summary":"string"}) }),
  ModuleMenuEntry: Object.freeze({ type: "object", fields: Object.freeze(["name","parent","title","path","icon","component","permission","sort","hidden"]), required: Object.freeze(["name","parent","title","path","icon","component","permission","sort","hidden"]), fieldTypes: Object.freeze({"name":"string","parent":"string","title":"string","path":"string","icon":"string","component":"string","permission":"string","sort":"number","hidden":"boolean"}) }),
  ModuleFrontendRoute: Object.freeze({ type: "object", fields: Object.freeze(["name","path","component","title","permission"]), required: Object.freeze(["name","path","component","title","permission"]), fieldTypes: Object.freeze({"name":"string","path":"string","component":"string","title":"string","permission":"string"}) }),
  ModuleMigrationSet: Object.freeze({ type: "object", fields: Object.freeze(["driver","dir","seeds_dir"]), required: Object.freeze(["driver","dir","seeds_dir"]), fieldTypes: Object.freeze({"driver":"string","dir":"string","seeds_dir":"string"}) }),
  ModuleList: Object.freeze({ type: "array", fields: Object.freeze([]), required: Object.freeze([]), itemType: "Module" }),
  DictionaryItem: Object.freeze({ type: "object", fields: Object.freeze(["label","value","sort"]), required: Object.freeze(["label","value","sort"]), fieldTypes: Object.freeze({"label":"string","value":"string","sort":"number"}) }),
  Dictionary: Object.freeze({ type: "object", fields: Object.freeze(["id","code","name","items","created_at","updated_at"]), required: Object.freeze(["id","code","name","items","created_at","updated_at"]), fieldTypes: Object.freeze({"id":"number","code":"string","name":"string","items":"array","created_at":"string","updated_at":"string"}), arrayItemTypes: Object.freeze({"items":"DictionaryItem"}) }),
  DictionaryList: Object.freeze({ type: "array", fields: Object.freeze([]), required: Object.freeze([]), itemType: "Dictionary" }),
  Setting: Object.freeze({ type: "object", fields: Object.freeze(["id","key","value","description","created_at","updated_at"]), required: Object.freeze(["id","key","value","description","created_at","updated_at"]), fieldTypes: Object.freeze({"id":"number","key":"string","description":"string","created_at":"string","updated_at":"string"}) }),
  SettingList: Object.freeze({ type: "array", fields: Object.freeze([]), required: Object.freeze([]), itemType: "Setting" }),
  AuditLog: Object.freeze({ type: "object", fields: Object.freeze(["id","actor_id","actor","action","resource","resource_id","ip","user_agent","detail","created_at"]), required: Object.freeze(["id","actor_id","actor","action","resource","resource_id","ip","user_agent","detail","created_at"]), fieldTypes: Object.freeze({"id":"number","actor_id":"number","actor":"string","action":"string","resource":"string","resource_id":"string","ip":"string","user_agent":"string","detail":"string","created_at":"string"}) }),
  AuditLogPage: Object.freeze({ type: "object", fields: Object.freeze(["items","total","page","page_size"]), required: Object.freeze(["items","total","page","page_size"]), fieldTypes: Object.freeze({"items":"array","total":"number","page":"number","page_size":"number"}), arrayItemTypes: Object.freeze({"items":"AuditLog"}) }),
  OkResult: Object.freeze({ type: "object", fields: Object.freeze(["ok"]), required: Object.freeze(["ok"]), fieldTypes: Object.freeze({"ok":"boolean"}) }),
  UpdateProfileRequest: Object.freeze({ type: "object", fields: Object.freeze(["nickname","email","phone","avatar"]), required: Object.freeze([]), fieldTypes: Object.freeze({"nickname":"string","email":"string","phone":"string","avatar":"string"}) }),
  ChangePasswordRequest: Object.freeze({ type: "object", fields: Object.freeze(["current_password","new_password"]), required: Object.freeze(["current_password","new_password"]), fieldTypes: Object.freeze({"current_password":"string","new_password":"string"}) }),
  CreateUserRequest: Object.freeze({ type: "object", fields: Object.freeze(["username","password","nickname","email","phone","avatar","role_ids","status"]), required: Object.freeze(["username","password"]), fieldTypes: Object.freeze({"username":"string","password":"string","nickname":"string","email":"string","phone":"string","avatar":"string","role_ids":"array","status":"string"}), arrayScalarItemTypes: Object.freeze({"role_ids":"number"}) }),
  UpdateUserRequest: Object.freeze({ type: "object", fields: Object.freeze(["username","password","nickname","email","phone","avatar","role_ids","status"]), required: Object.freeze(["username"]), fieldTypes: Object.freeze({"username":"string","password":"string","nickname":"string","email":"string","phone":"string","avatar":"string","role_ids":"array","status":"string"}), arrayScalarItemTypes: Object.freeze({"role_ids":"number"}) }),
  UserStatusRequest: Object.freeze({ type: "object", fields: Object.freeze(["status"]), required: Object.freeze(["status"]), fieldTypes: Object.freeze({"status":"string"}), enumValues: Object.freeze({"status":["active","disabled"]}) }),
  RoleRequest: Object.freeze({ type: "object", fields: Object.freeze(["name","code","description","permissions"]), required: Object.freeze(["name","code"]), fieldTypes: Object.freeze({"name":"string","code":"string","description":"string","permissions":"array"}), arrayScalarItemTypes: Object.freeze({"permissions":"string"}) }),
  MenuRequest: Object.freeze({ type: "object", fields: Object.freeze(["parent_id","title","name","path","icon","component","permission","sort","hidden"]), required: Object.freeze(["title","name","path"]), fieldTypes: Object.freeze({"parent_id":"number","title":"string","name":"string","path":"string","icon":"string","component":"string","permission":"string","sort":"number","hidden":"boolean"}) }),
  DictionaryRequest: Object.freeze({ type: "object", fields: Object.freeze(["code","name","items"]), required: Object.freeze(["code","name"]), fieldTypes: Object.freeze({"code":"string","name":"string","items":"array"}), arrayScalarItemTypes: Object.freeze({"items":"object"}), arrayObjectItemFields: Object.freeze({"items":["label","value","sort"]}), arrayObjectItemRequiredFields: Object.freeze({"items":["label","value"]}), arrayObjectItemFieldTypes: Object.freeze({"items":{"label":"string","value":"string","sort":"number"}}) }),
  SettingRequest: Object.freeze({ type: "object", fields: Object.freeze(["key","value","description"]), required: Object.freeze(["key"]), fieldTypes: Object.freeze({"key":"string","description":"string"}) }),
});
