// Code generated by scripts/generate-web-api-contract.mjs. DO NOT EDIT.

export const permissions = Object.freeze({
  all: "*",
  dashboardView: "dashboard:view",
  systemUserList: "system:user:list",
  systemUserCreate: "system:user:create",
  systemUserUpdate: "system:user:update",
  systemUserDelete: "system:user:delete",
  systemRoleList: "system:role:list",
  systemRoleCreate: "system:role:create",
  systemRoleUpdate: "system:role:update",
  systemRoleDelete: "system:role:delete",
  systemMenuList: "system:menu:list",
  systemMenuCreate: "system:menu:create",
  systemMenuUpdate: "system:menu:update",
  systemMenuDelete: "system:menu:delete",
  systemModuleList: "system:module:list",
  systemDictionaryList: "system:dictionary:list",
  systemDictionaryCreate: "system:dictionary:create",
  systemDictionaryUpdate: "system:dictionary:update",
  systemDictionaryDelete: "system:dictionary:delete",
  systemSettingList: "system:setting:list",
  systemSettingCreate: "system:setting:create",
  systemSettingUpdate: "system:setting:update",
  systemSettingDelete: "system:setting:delete",
  systemAuditList: "system:audit:list",
});

export const knownPermissions = Object.freeze(Object.values(permissions));
